In [23]:
import numpy as np

In [35]:
a = [[1,2,3],[1,2,3],[1,2,3]]
b = [[4,5,6],[4,5,6],[4,5,6]]

c = []

for i in range(len(a)):
    x = []
    for j in range(len(a[i])):
        x.append(a[i][j]*b[i][j])
    c.append(x)
print(c)

[[4, 10, 18], [4, 10, 18], [4, 10, 18]]


In [36]:
list(zip(a,b))

[([1, 2, 3], [4, 5, 6]), ([1, 2, 3], [4, 5, 6]), ([1, 2, 3], [4, 5, 6])]

In [37]:
[[q[0]*q[1] for q in zip(e[0],e[1])] for e in zip(a,b) ]

[[4, 10, 18], [4, 10, 18], [4, 10, 18]]

In [38]:
x = np.array(a)
y = np.array(b)
print(type(a), type(x))

<class 'list'> <class 'numpy.ndarray'>


In [39]:
print(x.shape, x.dtype)

(3, 3) int64


In [42]:
np.array([[[1,2,3]]]).shape

(1, 1, 3)

In [43]:
# https://www.numpy.org/
x * y

array([[ 4, 10, 18],
       [ 4, 10, 18],
       [ 4, 10, 18]])

In [45]:
x + y

array([[5, 7, 9],
       [5, 7, 9],
       [5, 7, 9]])

In [52]:
(x*y)[:,1]

array([10, 10, 10])

In [63]:
print(x)
print(np.sum(x, axis=1))
print(np.sum(x, axis=0))


[[1 2 3]
 [1 2 3]
 [1 2 3]]
[6 6 6]
[3 6 9]


In [65]:
print(np.add(x,y)) 
print(x + y)

[[5 7 9]
 [5 7 9]
 [5 7 9]]
[[5 7 9]
 [5 7 9]
 [5 7 9]]


In [72]:
print(np.ones((10,5)))
print(np.zeros((10,5)))
print(np.ones((10,5)).dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64


In [75]:
np.random.random((2,2,2,2,2,2))

array([[[[[[0.16199544, 0.40879894],
           [0.61708812, 0.43500552]],

          [[0.16649164, 0.99257456],
           [0.04905079, 0.33675552]]],


         [[[0.04160319, 0.15591006],
           [0.74815029, 0.27696947]],

          [[0.20120938, 0.95166286],
           [0.38106619, 0.6298887 ]]]],



        [[[[0.58104287, 0.1892685 ],
           [0.31704928, 0.64989372]],

          [[0.20040869, 0.94886523],
           [0.34131616, 0.38977157]]],


         [[[0.69850309, 0.13658444],
           [0.04433546, 0.85720762]],

          [[0.50269936, 0.3335567 ],
           [0.81618116, 0.10755243]]]]],




       [[[[[0.73157918, 0.32753776],
           [0.68108022, 0.89688349]],

          [[0.44502378, 0.72787237],
           [0.54924351, 0.16899473]]],


         [[[0.69987469, 0.11348275],
           [0.88563113, 0.98040468]],

          [[0.12625651, 0.52844659],
           [0.88565635, 0.03051228]]]],



        [[[[0.25938183, 0.15400673],
           [0.99184057, 0.12719

In [81]:
v = np.random.random((3,3))
print(v)

[[0.64940225 0.18150265 0.27293362]
 [0.89945864 0.44539945 0.79121472]
 [0.89462116 0.56725666 0.93434329]]


In [87]:
s = [e+2 for e in v.shape]
print(s)
w = np.ones(s)

[5, 5]


In [90]:
w[1:4,1:4] = v
print(w)

[[1.         1.         1.         1.         1.        ]
 [1.         0.64940225 0.18150265 0.27293362 1.        ]
 [1.         0.89945864 0.44539945 0.79121472 1.        ]
 [1.         0.89462116 0.56725666 0.93434329 1.        ]
 [1.         1.         1.         1.         1.        ]]


In [101]:
def withMarco(a, marco=1, ones=True):
    s = [e+marco*2 for e in a.shape]
    w = np.ones(s) if ones else np.zeros(s)
    w[marco:len(a)+marco,marco:len(a)+marco] = a
    return w


withMarco(np.random.random((1,1)), marco=2)
    

array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 0.62673365, 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ]])