In [3]:
import pandas as pd
import numpy as np

In [5]:
a = np.random.random((10,4))
print(a)

[[0.40391092 0.78806006 0.17446499 0.39234748]
 [0.90953438 0.30315952 0.37656784 0.40835709]
 [0.86140945 0.40952889 0.81769165 0.40518512]
 [0.45134735 0.00140125 0.45673096 0.95113883]
 [0.36667994 0.57761594 0.39048445 0.77475238]
 [0.61486036 0.04927868 0.75745351 0.98124269]
 [0.13030033 0.11107242 0.42752299 0.19022932]
 [0.35852416 0.52865543 0.89829051 0.06372047]
 [0.47737295 0.21994456 0.62441232 0.0252532 ]
 [0.69005779 0.23206245 0.78035091 0.9237278 ]]


In [11]:
x = pd.DataFrame(a, columns=["Uno","Dos","Tres","Cuatro"])
display(x)

Uno       Dos      Tres    Cuatro
0  0.403911  0.788060  0.174465  0.392347
1  0.909534  0.303160  0.376568  0.408357
2  0.861409  0.409529  0.817692  0.405185
3  0.451347  0.001401  0.456731  0.951139
4  0.366680  0.577616  0.390484  0.774752
5  0.614860  0.049279  0.757454  0.981243
6  0.130300  0.111072  0.427523  0.190229
7  0.358524  0.528655  0.898291  0.063720
8  0.477373  0.219945  0.624412  0.025253
9  0.690058  0.232062  0.780351  0.923728

In [15]:
print(x["Tres"])
type(x,x["Tres"])

0    0.174465
1    0.376568
2    0.817692
3    0.456731
4    0.390484
5    0.757454
6    0.427523
7    0.898291
8    0.624412
9    0.780351
Name: Tres, dtype: float64


TypeError: type() takes 1 or 3 arguments

In [18]:
hotels = pd.DataFrame({
    "Nombre Hotel":["Palas","Ritz","Sheraton","Pension Mari"],
    "Estrellas":[5,5,5,1],
    "Precio":[800,900,850,30]
})
display(hotels)

Nombre Hotel  Estrellas  Precio
0         Palas          5     800
1          Ritz          5     900
2      Sheraton          5     850
3  Pension Mari          1      30

In [19]:
hotels.dtypes

Nombre Hotel    object
Estrellas        int64
Precio           int64
dtype: object

In [20]:
hotels.shape

(4, 3)

In [25]:
hotels["Ratio"] = hotels["Estrellas"] / hotels["Precio"]
display(hotels.transpose())
display(hotels)


0           1           2             3
Nombre Hotel    Palas        Ritz    Sheraton  Pension Mari
Estrellas           5           5           5             1
Precio            800         900         850            30
Ratio         0.00625  0.00555556  0.00588235     0.0333333

Nombre Hotel  Estrellas  Precio     Ratio
0         Palas          5     800  0.006250
1          Ritz          5     900  0.005556
2      Sheraton          5     850  0.005882
3  Pension Mari          1      30  0.033333

In [26]:
hotels.sum()

Nombre Hotel    PalasRitzSheratonPension Mari
Estrellas                                  16
Precio                                   2580
Ratio                               0.0510212
dtype: object

In [28]:
print(
    hotels["Precio"].sum(),
    hotels["Precio"].max(),
    hotels["Precio"].min(),
    hotels["Precio"].mean()
)

2580 900 30 645.0


In [31]:
hotels.describe()

Estrellas      Precio     Ratio
count        4.0    4.000000  4.000000
mean         4.0  645.000000  0.012755
std          2.0  412.027507  0.013722
min          1.0   30.000000  0.005556
25%          4.0  607.500000  0.005801
50%          5.0  825.000000  0.006066
75%          5.0  862.500000  0.013021
max          5.0  900.000000  0.033333

In [32]:
hotels.describe().transpose()["min"]

Estrellas     1.000000
Precio       30.000000
Ratio         0.005556
Name: min, dtype: float64

In [42]:
pd.read_csv('./data/alumnos.csv')

Nombre  Edad
0  Pe,,pe    10
1    Juan    20
2    Luis    25
3    Fran  15xº

In [48]:
#https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_json.html
pd.read_json('./data/alumnos.json')

aficiones  edad nombre
0  [{'name': 'Beisbol', 'level': 2}, {'name': 'Fu...    10   Pepe

In [51]:
m = pd.read_csv('./data/alumnos.csv')
m.to_json('./data/alumnos_export.json', orient="records")

In [53]:
# pip3 install openpyxl
m.to_excel('./data/alumnos_export.xlsx')

In [66]:
import json

a = {
    "nombre":"Pepe",
    "apellidos":"Garcia"
}

b = json.dumps(a)
print(a)
print(b)
print(type(a),type(b))
print(a["nombre"])
#print(b["nombre"]) #  B is a string
m = json.loads(b)
print(m["nombre"])




{'nombre': 'Pepe', 'apellidos': 'Garcia'}
{"nombre": "Pepe", "apellidos": "Garcia"}
<class 'dict'> <class 'str'>
Pepe
Pepe


In [72]:
q = """
{
"nombre": "Pepe",
"apellidos": "Garcia"
}
"""

json.loads(q)

{'nombre': 'Pepe', 'apellidos': 'Garcia'}

In [77]:
class Mando:
    def __init__(self,marca="Casio"):
        self.marca=marca
    def cambiaMarca(self,marca):
        self.marca="Nuevamarca:"+marca

m = Mando()
print(m.__dict__)
print(json.dumps(m.__dict__))


{'marca': 'Casio'}
{"marca": "Casio"}
